audit issue L10
lindy-labs/sc_solidity-contracts pull request #197
Opened 2022-09-06 11:07 UTC by dxganta

removed the event emission since the backend is checking for the ETH & LQTY rewards contract balance periodically and not the event anyway.

2022-09-06 12:08 UTC, brkomir reviewed
please remove the event declaration and update the tests

2022-09-06 15:13 UTC, dxganta commented
> please remove the event declaration and update the tests

Fixed

2022-09-08 15:56 UTC, 0xrin1 requested changes
please don't merge this I need this event for our Liquity subgraph

I recommend closing this PR

2022-09-08 16:00 UTC, 0xrin1 approved these changes
nvm this event is for when we rebalance from strategy to vault, I thought it's when we claim rewards from liquity

LGTM

2022-09-09 07:07 UTC, brkomir commented
Just thinking, maybe all we need to do is to rename this event to something like `StrategyBalancesUpdated`, and have it emit new balances of LQTY and ETH...

2022-09-09 16:06 UTC, brkomir commented
To conclude, I suggest we remove this event and a new one called StrategyBalancesUpdated or something similar. It should be emitted in invest, harvest and at the end of the reinvest function. It should have total ETH and LQTY balances that are held by the strategy so that way we can always check the last event emitted to know what the current balances are. If that makes sense, we can go forward with the implementation

2022-09-12 06:56 UTC, dxganta commented
> To conclude, I suggest we remove this event and a new one called StrategyBalancesUpdated or something similar. It should be emitted in invest, harvest and at the end of the reinvest function, after the swaps and reinvest are done. It should have total ETH and LQTY balances that are held by the strategy as parameters, so that way we can always check the last event emitted to know what the current balances are. If that makes sense, we can go forward with the implementation



> To conclude, I suggest we remove this event and a new one called StrategyBalancesUpdated or something similar. It should be emitted in invest, harvest and at the end of the reinvest function, after the swaps and reinvest are done. It should have total ETH and LQTY balances that are held by the strategy as parameters, so that way we can always check the last event emitted to know what the current balances are. If that makes sense, we can go forward with the implementation

My only problem with this is, why do we need this event to check the current balances if we can check them by just querying the contract balances of the tokens?

2022-09-12 10:41 UTC, gabrielpoca commented
@brkomir @dxganta if you really need the events, you should already have transfer events for those ERC20. You don't need to emit new ones. But for the backend, querying the contracts is more reliable.

2022-09-13 10:28 UTC, dxganta commented
Too many merge conflicts. So I am closing this and creating a new one.

2022-09-13 10:28 UTC, closed without merging