Move from ropsten to goerli
lindy-labs/sc_solidity-contracts pull request #203
Opened 2022-09-08 10:26 UTC by gabrielpoca

2022-09-08 15:49 UTC, 0xrin1 requested changes

2022-09-08 15:49 UTC, 0xrin1 commented on deploy/vaultLUSD.ts
> +    '1111111111111111111111111111111111111111111111111111111111111111111111111111111111',
i'm guessing this was for debug

2022-09-08 15:49 UTC, 0xrin1 commented on deploy/vaultLUSD.ts
> +    '222222222222222222222222222222222222222222222222222222222222222222222222222222222222',
i'm guessing this was for debug

2022-09-09 09:25 UTC, 0xrin1 approved these changes

2022-09-12 10:44 UTC, gabrielpoca commented on deploy/vaultLUSD.ts
> +    '1111111111111111111111111111111111111111111111111111111111111111111111111111111111',
I'm an idiot 😁

2022-09-12 10:45 UTC, merged